services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: rtb
      POSTGRES_PASSWORD: rtbpass
      POSTGRES_DB: rtb
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rtb"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    expose:
      - "2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  ingester:
    build:
      context: .
      dockerfile: ./services/ingester/Dockerfile
    expose:
      - "9001"
    environment:
      SERVER_PORT: 9001
      KAFKA_BROKERS: "kafka:29092"
      KAFKA_TOPIC: "raw_metrics"
      LOG_LEVEL: "debug"
      LOG_FORMAT: "json"
      METRICS_USE_OTLP: "false"
    depends_on:
      kafka:
        condition: service_healthy

  pipeline:
    build:
      context: .
      dockerfile: ./services/pipeline/Dockerfile
    environment:
      KAFKA_BROKERS: "kafka:29092"
      KAFKA_TOPIC: "raw_metrics"
      LOG_LEVEL: "debug"
      LOG_FORMAT: "json"
    depends_on:
      kafka:
        condition: service_healthy

  aggregator:
    build:
      context: .
      dockerfile: ./services/aggregator/Dockerfile
    expose:
      - "9002"
    environment:
      SERVER_PORT: 9002
      DATABASE_DSN: "postgres://rtb:rtbpass@postgres:5432/rtb?sslmode=disable"
      LOG_LEVEL: "debug"
      LOG_FORMAT: "json"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: ./services/gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      GRPC_INGESTER: "ingester:9001"
      GRPC_AGGREGATOR: "http://aggregator:9002"
      LOG_LEVEL: "debug"
      LOG_FORMAT: "json"
    depends_on:
      - ingester
      - aggregator

volumes:
  pgdata: