// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/ingester/v1/ingester.proto

package ingesterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос: пакет метрик от одного источника.
type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`   // кто отправляет метрики (например, "web-server-1")
	Metrics       []*Metric              `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty"` // список метрик
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_proto_ingester_v1_ingester_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingester_v1_ingester_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_proto_ingester_v1_ingester_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *IngestRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Одна метрика.
type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                                               // http_requests_total
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`                                                                           // числовое значение
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // method=GET, status=200 и т.д.
	TimestampUnix int64                  `protobuf:"varint,4,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`                                       // время срабатывания метрики (Unix секунды)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_proto_ingester_v1_ingester_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingester_v1_ingester_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_proto_ingester_v1_ingester_proto_rawDescGZIP(), []int{1}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

// Ответ: подтверждение приёма.
type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"` // сколько метрик принято
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_proto_ingester_v1_ingester_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ingester_v1_ingester_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_proto_ingester_v1_ingester_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *IngestResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_proto_ingester_v1_ingester_proto protoreflect.FileDescriptor

const file_proto_ingester_v1_ingester_proto_rawDesc = "" +
	"\n" +
	" proto/ingester/v1/ingester.proto\x12\vingester.v1\"V\n" +
	"\rIngestRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12-\n" +
	"\ametrics\x18\x02 \x03(\v2\x13.ingester.v1.MetricR\ametrics\"\xcd\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x127\n" +
	"\x06labels\x18\x03 \x03(\v2\x1f.ingester.v1.Metric.LabelsEntryR\x06labels\x12%\n" +
	"\x0etimestamp_unix\x18\x04 \x01(\x03R\rtimestampUnix\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2[\n" +
	"\x0fIngesterService\x12H\n" +
	"\rIngestMetrics\x12\x1a.ingester.v1.IngestRequest\x1a\x1b.ingester.v1.IngestResponseBMZKgithub.com/system-highload-architect/qos-pipeline/pb/ingester/v1;ingesterv1b\x06proto3"

var (
	file_proto_ingester_v1_ingester_proto_rawDescOnce sync.Once
	file_proto_ingester_v1_ingester_proto_rawDescData []byte
)

func file_proto_ingester_v1_ingester_proto_rawDescGZIP() []byte {
	file_proto_ingester_v1_ingester_proto_rawDescOnce.Do(func() {
		file_proto_ingester_v1_ingester_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ingester_v1_ingester_proto_rawDesc), len(file_proto_ingester_v1_ingester_proto_rawDesc)))
	})
	return file_proto_ingester_v1_ingester_proto_rawDescData
}

var file_proto_ingester_v1_ingester_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ingester_v1_ingester_proto_goTypes = []any{
	(*IngestRequest)(nil),  // 0: ingester.v1.IngestRequest
	(*Metric)(nil),         // 1: ingester.v1.Metric
	(*IngestResponse)(nil), // 2: ingester.v1.IngestResponse
	nil,                    // 3: ingester.v1.Metric.LabelsEntry
}
var file_proto_ingester_v1_ingester_proto_depIdxs = []int32{
	1, // 0: ingester.v1.IngestRequest.metrics:type_name -> ingester.v1.Metric
	3, // 1: ingester.v1.Metric.labels:type_name -> ingester.v1.Metric.LabelsEntry
	0, // 2: ingester.v1.IngesterService.IngestMetrics:input_type -> ingester.v1.IngestRequest
	2, // 3: ingester.v1.IngesterService.IngestMetrics:output_type -> ingester.v1.IngestResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ingester_v1_ingester_proto_init() }
func file_proto_ingester_v1_ingester_proto_init() {
	if File_proto_ingester_v1_ingester_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ingester_v1_ingester_proto_rawDesc), len(file_proto_ingester_v1_ingester_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ingester_v1_ingester_proto_goTypes,
		DependencyIndexes: file_proto_ingester_v1_ingester_proto_depIdxs,
		MessageInfos:      file_proto_ingester_v1_ingester_proto_msgTypes,
	}.Build()
	File_proto_ingester_v1_ingester_proto = out.File
	file_proto_ingester_v1_ingester_proto_goTypes = nil
	file_proto_ingester_v1_ingester_proto_depIdxs = nil
}
